// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA3OptlG4gzsFNiI8eETvVcY1rf8iTbf4',
    appId: '1:191494620360:web:95978276961887614a51fd',
    messagingSenderId: '191494620360',
    projectId: 'teste-firebase-notifications',
    authDomain: 'teste-firebase-notifications.firebaseapp.com',
    storageBucket: 'teste-firebase-notifications.appspot.com',
    measurementId: 'G-T33R63SCLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSm2llatFSKb5wqxcw3BWl7fiXw3GLUXY',
    appId: '1:191494620360:android:72dd8e5f37bff75f4a51fd',
    messagingSenderId: '191494620360',
    projectId: 'teste-firebase-notifications',
    storageBucket: 'teste-firebase-notifications.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_-qaJ8RJrbZSsg9vK67xo_1kjks3_B7c',
    appId: '1:191494620360:ios:90d6d8a4994709c04a51fd',
    messagingSenderId: '191494620360',
    projectId: 'teste-firebase-notifications',
    storageBucket: 'teste-firebase-notifications.appspot.com',
    iosClientId: '191494620360-ou9j95qc97upij9grmobcskeu6gr3o3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_-qaJ8RJrbZSsg9vK67xo_1kjks3_B7c',
    appId: '1:191494620360:ios:90d6d8a4994709c04a51fd',
    messagingSenderId: '191494620360',
    projectId: 'teste-firebase-notifications',
    storageBucket: 'teste-firebase-notifications.appspot.com',
    iosClientId: '191494620360-ou9j95qc97upij9grmobcskeu6gr3o3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNotifications',
  );
}
